# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 15:20
from __future__ import unicode_literals

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171111_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[100, 100], upload_to='images/'),
        ),
    ]
