# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edict_data', models.CharField(max_length=256)),
            ],
        ),
    ]
