# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0002_dictionaryimportrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionaryimportrequest',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
