# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0004_auto_20171017_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionaryimportrequest',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dictionaryimportrequest',
            name='total_entries_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
