# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0005_auto_20171018_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionaryimportrequest',
            name='interrupted',
            field=models.BooleanField(default=False),
        ),
    ]
