# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0006_dictionaryimportrequest_interrupted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionaryentry',
            name='edict_data',
            field=models.CharField(max_length=2048),
        ),
    ]
