# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0007_auto_20171018_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingDictionaryImportRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='importer.DictionaryImportRequest')),
            ],
        ),
        migrations.RunSQL(
            "INSERT INTO importer_pendingdictionaryimportrequest DEFAULT VALUES;"
        ),
    ]
