# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0009_auto_20171021_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionaryentry',
            name='source_import_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='importer.DictionaryImportRequest'),
        ),
        migrations.AlterField(
            model_name='pendingdictionaryimportrequest',
            name='import_request',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='importer.DictionaryImportRequest'),
        ),
    ]
