# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0010_auto_20171021_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionaryentry',
            name='source_import_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importer.DictionaryImportRequest'),
        ),
    ]
