# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0012_auto_20171023_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invertedindexentry',
            old_name='word',
            new_name='index_word',
        ),
        migrations.AlterField(
            model_name='invertedindexentry',
            name='index_word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='importer.InvertedIndexWord'),
        ),
    ]
