# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0014_invertedindexentry_end_position'),
    ]

    operations = [
        # Remove existing foreign key constraints
        migrations.AlterField(
            model_name='dictionaryentry',
            name='source_import_request',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='importer.DictionaryImportRequest'),
        ),
        migrations.AlterField(
            model_name='invertedindexentry',
            name='dictionary_entry',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='importer.DictionaryEntry'),
        ),

        # Add new foreign key constraints with ON DELETE CASCADE
        migrations.RunSQL(
            """
            ALTER TABLE importer_dictionaryentry
            ADD CONSTRAINT importer_dictionaryentry_source_import_request_fk
            FOREIGN KEY (source_import_request_id)
            REFERENCES importer_dictionaryimportrequest (id)
            ON DELETE CASCADE;
            """,
            """
            ALTER TABLE importer_dictionaryentry
            DROP CONSTRAINT importer_dictionaryentry_source_import_request_fk
            """
        ),
        migrations.RunSQL(
            """
            ALTER TABLE importer_invertedindexentry
            ADD CONSTRAINT importer_invertedindexentry_dictionary_entry_fk
            FOREIGN KEY (dictionary_entry_id)
            REFERENCES importer_dictionaryentry (id)
            ON DELETE CASCADE;
            """,
            """
            ALTER TABLE importer_invertedindexentry
            DROP CONSTRAINT importer_invertedindexentry_dictionary_entry_fk
            """
        ),
    ]
