# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0015_auto_20171031_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invertedindexword',
            name='word',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
