# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0016_auto_20171107_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='invertedindexentry',
            name='index_word_text',
            field=models.CharField(db_index=True, default=None, max_length=128),
            preserve_default=False,
        ),
    ]
