# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0017_invertedindexentry_index_word_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invertedindexentry',
            name='index_word',
        ),
    ]
