# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0018_remove_invertedindexentry_index_word'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvertedIndexWord',
        ),
    ]
