# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0019_delete_invertedindexword'),
    ]

    operations = [
        migrations.RunSQL(
            # entries prior to this migration have no known weight
            # and should be deleted
            "DELETE FROM importer_invertedindexentry;"
        ),
        migrations.AddField(
            model_name='invertedindexentry',
            name='weight',
            field=models.FloatField(),
        ),
    ]
