# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0020_invertedindexentry_weight'),
    ]

    operations = [
        migrations.RunSQL(
            # entries prior to this migration have no en_text
            # or jp_text and should be deleted
            "DELETE FROM importer_dictionaryentry;"
        ),
        migrations.RemoveField(
            model_name='dictionaryentry',
            name='edict_data',
        ),
        migrations.AddField(
            model_name='dictionaryentry',
            name='en_text',
            field=models.CharField(max_length=2048),
        ),
        migrations.AddField(
            model_name='dictionaryentry',
            name='jp_text',
            field=models.CharField(max_length=2048),
        ),
    ]
