# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0021_auto_20171203_1454'),
    ]

    operations = [
        migrations.RunSQL(
            # entries prior to this migration have no en_text
            # or jp_text and should be deleted
            "DELETE FROM importer_invertedindexentry;"
        ),
        migrations.AddField(
            model_name='invertedindexentry',
            name='index_column',
            field=models.CharField(max_length=128),
        ),
    ]
