# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0023_dictionaryentry_meta_text'),
    ]

    operations = [
        migrations.RunSQL(
            # entries prior to this migration have no known
            # sequence_number and should be deleted
            "DELETE FROM importer_dictionaryentry;"
        ),
        migrations.AddField(
            model_name='dictionaryentry',
            name='sequence_number',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
