# Generated by Django 2.0 on 2017-12-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0024_dictionaryentry_sequence_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invertedindexentry',
            name='index_word_text',
            field=models.CharField(db_index=True, max_length=256),
        ),
    ]
