# Generated by Django 2.0 on 2018-01-04 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0027_auto_20180104_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invertedindexentry',
            name='index_column',
        ),
    ]
