# Generated by Django 2.0.1 on 2018-01-07 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0028_remove_invertedindexentry_index_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionaryentry',
            name='source_import_request',
        ),
        migrations.RemoveField(
            model_name='invertedindexentry',
            name='dictionary_entry',
        ),
        migrations.DeleteModel(
            name='DictionaryEntry',
        ),
        migrations.DeleteModel(
            name='InvertedIndexEntry',
        ),
    ]
