# Generated by Django 2.0.1 on 2018-01-23 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0029_auto_20180107_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jp_text', models.CharField(max_length=2048)),
                ('en_text', models.CharField(max_length=2048)),
                ('meta_text', models.CharField(max_length=2048)),
                ('sequence_number', models.PositiveIntegerField(db_index=True)),
                ('frequency_rank', models.PositiveIntegerField(db_index=True)),
                ('common', models.BooleanField(db_index=True)),
                ('source_import_request', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='importer.DictionaryImportRequest')),
            ],
        ),
        migrations.CreateModel(
            name='InvertedIndexEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_word_text', models.CharField(db_index=True, max_length=256)),
                ('weight', models.FloatField()),
                ('dictionary_entry', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='importer.DictionaryEntry')),
            ],
        ),
    ]
